# Titanic Dataset

In [24]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [25]:
data = pd.read_csv('/content/Titanic-Dataset.csv')
data = data.drop(['Name', 'Ticket', 'Cabin'], axis=1)

In [26]:
data

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0              1         0       3    male  22.0      1      0   7.2500        S
1              2         1       1  female  38.0      1      0  71.2833        C
2              3         1       3  female  26.0      0      0   7.9250        S
3              4         1       1  female  35.0      1      0  53.1000        S
4              5         0       3    male  35.0      0      0   8.0500        S
..           ...       ...     ...     ...   ...    ...    ...      ...      ...
886          887         0       2    male  27.0      0      0  13.0000        S
887          888         1       1  female  19.0      0      0  30.0000        S
888          889         0       3  female   NaN      1      2  23.4500        S
889          890         1       1    male  26.0      0      0  30.0000        C
890          891         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 9 columns]

In [27]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked         2
dtype: int64

In [28]:
data['Age'] = data['Age'].fillna(data['Age'].median())
data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

In [29]:
data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [30]:
data['Sex'] = data['Sex'].map({'male': 0, 'female': 1})

data['Embarked'] = data['Embarked'].map({'C': 0, 'Q': 1, 'S': 2})

In [31]:
X = data[['Age']]
y = data['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
logistic_model = LogisticRegression(max_iter=200)
logistic_model.fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

In [33]:
print("Accuracy of the Logistic Regression model:", accuracy)
print("Confusion Matrix:")
print(confusion)

Accuracy of the Logistic Regression model: 0.5865921787709497
Confusion Matrix:
[[105   0]
 [ 74   0]]